/**
 * output.service.ts
 *
 * Responsible for persisting every AI-generated artifact (summaries, flashcards,
 * quiz questions, quiz results) to disk inside /output/ at the workspace root.
 *
 * Directory layout:
 *   output/
 *     generated_files/  – summaries, flashcards, quizzes generated by AI
 *     saved_results/    – graded quiz results submitted by users
 */

import fs from "fs";
import path from "path";

// ─── Resolve output root ────────────────────────────────────────────────────
// API server runs from artifacts/api-server, so ../../.. reaches workspace root.
const WORKSPACE_ROOT = path.resolve(process.cwd(), "../..");
const GENERATED_DIR  = path.join(WORKSPACE_ROOT, "output", "generated_files");
const RESULTS_DIR    = path.join(WORKSPACE_ROOT, "output", "saved_results");

// Ensure directories exist at startup
[GENERATED_DIR, RESULTS_DIR].forEach(dir => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

// ─── Types ──────────────────────────────────────────────────────────────────

export type OutputType = "summary" | "flashcards" | "quiz" | "pdf-quiz";

export interface SavedFile {
  filename: string;
  type: string;
  userId: number;
  topic?: string;
  createdAt: string;
  downloadPath: string;
  sizeBytes: number;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function nanoid(len = 8): string {
  return Math.random().toString(36).slice(2, 2 + len);
}

function timestamp(): string {
  return new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
}

function writeJson(dir: string, filename: string, data: object): void {
  fs.writeFileSync(path.join(dir, filename), JSON.stringify(data, null, 2), "utf8");
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Save AI-generated content (summary / flashcards / quiz).
 * Returns the filename so it can be included in the API response.
 */
export function saveGeneratedFile(
  type: OutputType,
  userId: number,
  content: object,
  topic?: string,
): string {
  const filename = `${type}_${timestamp()}_${nanoid()}.json`;
  const payload = {
    _meta: { type, userId, topic: topic ?? null, createdAt: new Date().toISOString() },
    ...content,
  };
  writeJson(GENERATED_DIR, filename, payload);
  return filename;
}

/**
 * Save a graded quiz result.
 * Returns the filename.
 */
export function saveQuizResult(
  userId: number,
  content: object,
  topic?: string,
): string {
  const filename = `result_${timestamp()}_${nanoid()}.json`;
  const payload = {
    _meta: { type: "result", userId, topic: topic ?? null, createdAt: new Date().toISOString() },
    ...content,
  };
  writeJson(RESULTS_DIR, filename, payload);
  return filename;
}

/**
 * List all files in both output directories, sorted newest-first.
 */
export function listAllOutputFiles(userId?: number): SavedFile[] {
  const readDir = (dir: string, subdir: string): SavedFile[] => {
    if (!fs.existsSync(dir)) return [];
    return fs.readdirSync(dir)
      .filter(f => f.endsWith(".json"))
      .map(filename => {
        const fullPath = path.join(dir, filename);
        const stat = fs.statSync(fullPath);
        let meta: Record<string, any> = {};
        try {
          const raw = JSON.parse(fs.readFileSync(fullPath, "utf8"));
          meta = raw._meta ?? {};
        } catch {}
        return {
          filename,
          type: meta.type ?? subdir,
          userId: meta.userId ?? 0,
          topic: meta.topic ?? undefined,
          createdAt: meta.createdAt ?? stat.mtime.toISOString(),
          downloadPath: `/api/output-history/download/${subdir}/${filename}`,
          sizeBytes: stat.size,
        };
      })
      .filter(f => userId == null || f.userId === userId);
  };

  const all = [
    ...readDir(GENERATED_DIR, "generated"),
    ...readDir(RESULTS_DIR, "results"),
  ];

  all.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  return all;
}

/**
 * Read the raw content of an output file.
 */
export function readOutputFile(subdir: "generated" | "results", filename: string): object | null {
  const dir = subdir === "generated" ? GENERATED_DIR : RESULTS_DIR;
  const fullPath = path.join(dir, filename);
  if (!fs.existsSync(fullPath)) return null;
  try {
    return JSON.parse(fs.readFileSync(fullPath, "utf8"));
  } catch {
    return null;
  }
}

export { GENERATED_DIR, RESULTS_DIR };
